### PR TITLE
Add support for catalog file

### PR DESCRIPTION
**Pull request by zybreak**
Backport of catalog file support from ewerk branch

### CODE REVIEW

**Comment by deepy** [comment]
Initially I forked it with this support, but the way it was implemented meant that the catalog was not optional so I had to remove it.

I'm a bit short on time this week, but I can work on getting that fixed next week, my own initial use-case didn't require it so I opted for the lazy way (which was waiting for an upstreams fix)

**Comment by zybreak** [comment]
Ah, I see. I updated the PR so the `catalog` argument is now optional

**Comment by deepy** [comment]
Works great! Thank you for the PR :-)

**Comment by deepy** [comment]
0.2.0 has been released with this fix.

**Comment by zybreak** [comment]
Thanks!

**Pull request merged**
