### PR TITLE
updated jaxb2 libraries and gradle as well as added testing

### PR DESCRIPTION
**Pull request by zybreak**
I couldn't help myself and updated both jaxb and jaxb2 to newer versions (this fixes an issue where catalog-support required adding an extra jaxb dependency when using the plugin together with catalog-files)

I also went ahead and upgraded gradle to the latest version and added a simple functional test with gradles TestKit

I'm not sure if this is of any benefit to you, but i might as well create a PR and let you decide for yourself

### CODE REVIEW

**Comment by deepy** [comment]
This looks great!

Although when I test it locally I get a mysterious failure, I'll see if I can figure out what goes wrong.

```java
Caused by: : xjc failed
        at com.sun.tools.xjc.XJCBase.execute(XJCBase.java:731)
        at com.sun.tools.xjc.XJC2Task.execute(XJC2Task.java:55)
        at org.jvnet.jaxb2_commons.xjc.XJC2Task.execute(XJC2Task.java:35)
```

**Comment by deepy** [comment]
The upgrade from `JAXB_VERSION = '2.2.11'` seems to be the immediate cause

**Comment by deepy** [comment]
With `ant.lifecycleLogLevel = "INFO/VERBOSE"` I managed to get it to print `[ant:xjc] failure in the XJC task. Use the Ant -verbose switch for more details` but no matter what I do I can't seem to get the -verbose switch to ant :p

**Comment by zybreak** [comment]
It might have been a bad idea for me to add the TestKit-tests. Even though they're great for integration testing, since they actually download and execute the actual gradle task specified in the test, i'm sure there is also a a lot of things that could go wrong causing it to be too shaky to be useful.

Maybe the best thing is to ignore the test from the test-suite.

**Comment by deepy** [comment]
The issue isn't the tests, I'm triggering it in a normal project.

The problem is I can't figure out how to get Gradle to tell me what goes wrong

**Pull request closed without merging**
